---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to remove wget
    yum:
      name: wget
      state: present
      when: ansible_is_family=="RedHat"
  - name: I want to remove wget
    apt:
      name: wget
      state: present
      when: ansible_is_family=="Debian"