---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to remove wget
      service:
        name: wget
        state: absent
        when: ansible_is_family == "RedHat"
  - name: I want to remove wget
      service:
        name: wget
        state: absent
        when: ansible_is_family == "Debian"